name: pysal
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.6
  - libpysal >=4.3.0
  - esda >=2.3.0
  - giddy >=2.3.3
  - inequality >=1.0.0
  - pointpats >=2.1.0
  - segregation >=1.3.0
  - spaghetti >=1.5.0
  - mgwr >=2.1.1
  - spglm >=1.0.7
  - spint >=1.0.6
  - spreg >=1.1.1
  - spvcm >=0.3.0
  - tobler >=0.3.1
  - mapclassify >=2.3.0
  - splot >=1.1.3
  - access >=1.1.1
  - urllib3 >=1.26
